In [1]:
import pandas as pd
temp = pd.read_csv('Toronto_temp.csv', sep=',')

In [2]:
## PANDAS

In [3]:
#1
temp.head()

,Date/Time,Year,Month,Day,Mean Temp (C),Max Temp (C),Min Temp (C),Total Rain (mm),Total Snow (cm),Total Precip (mm),season
0,31-Jan-18,"2,018",1,31,-7.0,2.0,-15.0,0.0,1.0,1.0,Winter
1,30-Jan-18,"2,018",1,30,-11.0,-7.0,-15.0,0.0,0.0,0.0,Winter
2,29-Jan-18,"2,018",1,29,-4.0,-2.0,-7.0,0.0,5.0,5.0,Winter
3,28-Jan-18,"2,018",1,28,1.0,5.0,-3.0,0.0,0.0,0.0,Winter
4,27-Jan-18,"2,018",1,27,5.0,10.0,0.0,2.0,0.0,2.0,Winter

In [4]:
#2
temp.tail()

,Date/Time,Year,Month,Day,Mean Temp (C),Max Temp (C),Min Temp (C),Total Rain (mm),Total Snow (cm),Total Precip (mm),season
2884,01-Dec-41,1941,12,1,-1.5,1.9,-4.8,24.9,16.3,41.1,Winter
2885,01-Dec-40,1940,12,1,-3.6,0.6,-7.7,68.1,14.5,82.6,Winter
2886,01-Dec-39,1939,12,1,NaN,NaN,NaN,NaN,NaN,NaN,Winter
2887,01-Dec-38,1938,12,1,-2.5,1.1,-6.1,13.7,13.7,27.4,Winter
2888,01-Dec-37,1937,12,1,-4.4,0.1,-8.8,7.6,33.8,41.4,Winter

In [5]:
#3
type(temp)

pandas.core.frame.DataFrame

In [6]:
#4
temp['season'].head()

0    Winter
1    Winter
2    Winter
3    Winter
4    Winter
Name: season, dtype: object

In [7]:
#5
temp.season.head()

0    Winter
1    Winter
2    Winter
3    Winter
4    Winter
Name: season, dtype: object

In [8]:
#6
temp.shape

(2889, 11)

In [9]:
#7
temp.dtypes

Date/Time             object
Year                  object
Month                  int64
Day                    int64
Mean Temp (C)        float64
Max Temp (C)         float64
Min Temp (C)         float64
Total Rain (mm)      float64
Total Snow (cm)      float64
Total Precip (mm)    float64
season                object
dtype: object

In [10]:
#8
temp.describe(include=['object'])

        Date/Time   Year  season
count        2889   2889    2889
unique       2889     83       4
top     01-May-51  2,016  Summer
freq            1    366     766

In [11]:
#9
temp.columns

Index(['Date/Time', 'Year', 'Month', 'Day', 'Mean Temp (C)', 'Max Temp (C)',
       'Min Temp (C)', 'Total Rain (mm)', 'Total Snow (cm)',
       'Total Precip (mm)', 'season'],
      dtype='object')

In [12]:
#10
temp_cols =['Date','Year','Month','Day','Mean_Temp_C','Max_Temp_C','Min_Temp_C','Rain_mm','Snow_cm','Precip','Season']
temp.columns = temp_cols
temp.head()

,Date,Year,Month,Day,Mean_Temp_C,Max_Temp_C,Min_Temp_C,Rain_mm,Snow_cm,Precip,Season
0,31-Jan-18,"2,018",1,31,-7.0,2.0,-15.0,0.0,1.0,1.0,Winter
1,30-Jan-18,"2,018",1,30,-11.0,-7.0,-15.0,0.0,0.0,0.0,Winter
2,29-Jan-18,"2,018",1,29,-4.0,-2.0,-7.0,0.0,5.0,5.0,Winter
3,28-Jan-18,"2,018",1,28,1.0,5.0,-3.0,0.0,0.0,0.0,Winter
4,27-Jan-18,"2,018",1,27,5.0,10.0,0.0,2.0,0.0,2.0,Winter

In [13]:
#11
temp.columns = temp.columns.str.replace('_',' ')
temp.columns

Index(['Date', 'Year', 'Month', 'Day', 'Mean Temp C', 'Max Temp C',
       'Min Temp C', 'Rain mm', 'Snow cm', 'Precip', 'Season'],
      dtype='object')

In [14]:
#12
temp.drop('Day', axis=1,inplace=True)
temp.head()

,Date,Year,Month,Mean Temp C,Max Temp C,Min Temp C,Rain mm,Snow cm,Precip,Season
0,31-Jan-18,"2,018",1,-7.0,2.0,-15.0,0.0,1.0,1.0,Winter
1,30-Jan-18,"2,018",1,-11.0,-7.0,-15.0,0.0,0.0,0.0,Winter
2,29-Jan-18,"2,018",1,-4.0,-2.0,-7.0,0.0,5.0,5.0,Winter
3,28-Jan-18,"2,018",1,1.0,5.0,-3.0,0.0,0.0,0.0,Winter
4,27-Jan-18,"2,018",1,5.0,10.0,0.0,2.0,0.0,2.0,Winter

In [15]:
#13
temp['Precip'].sort_values()

2057    0.0
1816    0.0
1817    0.0
936     0.0
935     0.0
       ...
2330    NaN
2339    NaN
2416    NaN
2655    NaN
2886    NaN
Name: Precip, Length: 2889, dtype: float64

In [16]:
#14
temp['Precip'].sort_values(ascending=False)

2401    213.9
2108    212.3
1131    208.5
1570    193.2
1307    191.6
        ...
2330      NaN
2339      NaN
2416      NaN
2655      NaN
2886      NaN
Name: Precip, Length: 2889, dtype: float64

In [17]:
#15
temp.sort_values('Season')

,Date,Year,Month,Mean Temp C,Max Temp C,Min Temp C,Rain mm,Snow cm,Precip,Season
2438,24-Nov-17,"2,017",11,6.0,12.0,0.0,0.0,0.0,0.0,Fall
1953,09-Sep-17,"2,017",9,13.0,18.0,8.0,0.0,0.0,0.0,Fall
1954,08-Sep-17,"2,017",9,14.0,19.0,10.0,0.0,0.0,0.0,Fall
1955,07-Sep-17,"2,017",9,15.0,20.0,10.0,4.0,0.0,4.0,Fall
1956,06-Sep-17,"2,017",9,16.0,21.0,11.0,0.0,0.0,0.0,Fall
...,...,...,...,...,...,...,...,...,...,...
304,12-Feb-16,"2,016",2,-10.0,-4.0,-16.0,0.0,1.0,1.0,Winter
305,11-Feb-16,"2,016",2,-13.0,-10.0,-17.0,0.0,0.0,0.0,Winter
306,10-Feb-16,"2,016",2,-7.0,-1.0,-12.0,0.0,1.0,1.0,Winter
224,01-Jan-44,1944,1,-2.7,1.4,-6.8,10.4,9.7,20.1,Winter
2888,01-Dec-37,1937,12,-4.4,0.1,-8.8,7.6,33.8,41.4,Winter

In [18]:
#16
booleans =[]

for length in temp.Precip:
    if length >=2.0:
        booleans.append(True)
    else:
        booleans.append(False)

booleans[0:5]

[False, False, True, False, True]

In [19]:
#17
len(booleans)

2889

In [20]:
#18
is_long = temp.Precip>= 2.0
is_long.head()

0    False
1    False
2     True
3    False
4     True
Name: Precip, dtype: bool

In [21]:
#19
temp[temp.Precip >= 2]

,Date,Year,Month,Mean Temp C,Max Temp C,Min Temp C,Rain mm,Snow cm,Precip,Season
2,29-Jan-18,"2,018",1,-4.0,-2.0,-7.0,0.0,5.0,5.0,Winter
4,27-Jan-18,"2,018",1,5.0,10.0,0.0,2.0,0.0,2.0,Winter
8,23-Jan-18,"2,018",1,1.0,7.0,-5.0,3.0,0.0,3.0,Winter
9,22-Jan-18,"2,018",1,2.0,2.0,1.0,14.0,0.0,14.0,Winter
16,15-Jan-18,"2,018",1,-8.0,-7.0,-9.0,0.0,4.0,4.0,Winter
...,...,...,...,...,...,...,...,...,...,...
2883,01-Dec-42,1942,12,-5.6,-1.8,-9.4,56.4,53.6,110.0,Winter
2884,01-Dec-41,1941,12,-1.5,1.9,-4.8,24.9,16.3,41.1,Winter
2885,01-Dec-40,1940,12,-3.6,0.6,-7.7,68.1,14.5,82.6,Winter
2887,01-Dec-38,1938,12,-2.5,1.1,-6.1,13.7,13.7,27.4,Winter
2888,01-Dec-37,1937,12,-4.4,0.1,-8.8,7.6,33.8,41.4,Winter

In [22]:
#20
temp[(temp['Precip']>=2) & (temp['Season']=='Summer')]

,Date,Year,Month,Mean Temp C,Max Temp C,Min Temp C,Rain mm,Snow cm,Precip,Season
1139,27-Jun-18,"2,018",6,19.0,22.0,17.0,8.0,0.0,8.0,Summer
1142,24-Jun-18,"2,018",6,18.0,21.0,15.0,21.0,0.0,21.0,Summer
1143,23-Jun-18,"2,018",6,18.0,20.0,17.0,5.0,0.0,5.0,Summer
1144,22-Jun-18,"2,018",6,18.0,23.0,13.0,2.0,0.0,2.0,Summer
1148,18-Jun-18,"2,018",6,25.0,33.0,18.0,3.0,0.0,3.0,Summer
...,...,...,...,...,...,...,...,...,...,...
1897,01-Aug-42,1942,8,19.7,25.7,13.6,28.7,0.0,28.7,Summer
1898,01-Aug-41,1941,8,19.5,25.6,13.4,39.4,0.0,39.4,Summer
1899,01-Aug-40,1940,8,19.4,25.1,13.6,84.1,0.0,84.1,Summer
1900,01-Aug-39,1939,8,21.7,28.7,14.7,51.6,0.0,51.6,Summer
1901,01-Aug-38,1938,8,22.7,29.7,15.6,37.1,0.0,37.1,Summer

In [23]:
#21
for index, row in temp.iterrows():
    print(index, row.Year, row.Season)

0 2,018 Winter
1 2,018 Winter
2 2,018 Winter
3 2,018 Winter
4 2,018 Winter
5 2,018 Winter
6 2,018 Winter
7 2,018 Winter
8 2,018 Winter
9 2,018 Winter
10 2,018 Winter
11 2,018 Winter
12 2,018 Winter
13 2,018 Winter
14 2,018 Winter
15 2,018 Winter
16 2,018 Winter
17 2,018 Winter
18 2,018 Winter
19 2,018 Winter
20 2,018 Winter
21 2,018 Winter
22 2,018 Winter
23 2,018 Winter
24 2,018 Winter
25 2,018 Winter
26 2,018 Winter
27 2,018 Winter
28 2,018 Winter
29 2,018 Winter
30 2,018 Winter
31 2,017 Winter
32 2,017 Winter
33 2,017 Winter
34 2,017 Winter
35 2,017 Winter
36 2,017 Winter
37 2,017 Winter
38 2,017 Winter
39 2,017 Winter
40 2,017 Winter
41 2,017 Winter
42 2,017 Winter
43 2,017 Winter
44 2,017 Winter
45 2,017 Winter
46 2,017 Winter
47 2,017 Winter
48 2,017 Winter
49 2,017 Winter
50 2,017 Winter
51 2,017 Winter
52 2,017 Winter
53 2,017 Winter
54 2,017 Winter
55 2,017 Winter
56 2,017 Winter
57 2,017 Winter
58 2,017 Winter
59 2,017 Winter
60 2,017 Winter
61 2,017 Winter
62 2,016 Winter
63 2,016 Winter
64 2,016 Winter
65 2,016 Winter
66 2,016 Winter
67 2,016 Winter
68 2,016 Winter
69 2,016 Winter
70 2,016 Winter
71 2,016 Winter
72 2,016 Winter
73 2,016 Winter
74 2,016 Winter
75 2,016 Winter
76 2,016 Winter
77 2,016 Winter
78 2,016 Winter
79 2,016 Winter
80 2,016 Winter
81 2,016 Winter
82 2,016 Winter
83 2,016 Winter
84 2,016 Winter
85 2,016 Winter
86 2,016 Winter
87 2,016 Winter
88 2,016 Winter
89 2,016 Winter
90 2,016 Winter
91 2,016 Winter
92 2,016 Winter
93 2,015 Winter
94 2,015 Winter
95 2,015 Winter
96 2,015 Winter
97 2,015 Winter
98 2,015 Winter
99 2,015 Winter
100 2,015 Winter
101 2,015 Winter
102 2,015 Winter
103 2,015 Winter
104 2,015 Winter
105 2,015 Winter
106 2,015 Winter
107 2,015 Winter
108 2,015 Winter
109 2,015 Winter
110 2,015 Winter
111 2,015 Winter
112 2,015 Winter
113 2,015 Winter
114 2,015 Winter
115 2,015 Winter
116 2,015 Winter
117 2,015 Winter
118 2,015 Winter
119 2,015 Winter
120 2,015 Winter
121 2,015 Winter
122 2,015 Winter
123 2,015 Winter
124 2,014 Winter
125 2,014 Winter
126 2,014 Winter
127 2,014 Winter
128 2,014 Winter
129 2,014 Winter
130 2,014 Winter
131 2,014 Winter
132 2,014 Winter
133 2,014 Winter
134 2,014 Winter
135 2,014 Winter
136 2,014 Winter
137 2,014 Winter
138 2,014 Winter
139 2,014 Winter
140 2,014 Winter
141 2,014 Winter
142 2,014 Winter
143 2,014 Winter
144 2,014 Winter
145 2,014 Winter
146 2,014 Winter
147 2,014 Winter
148 2,014 Winter
149 2,014 Winter
150 2,014 Winter
151 2,014 Winter
152 2,014 Winter
153 2,014 Winter
154 2,014 Winter
155 2013 Winter
156 2012 Winter
157 2011 Winter
158 2010 Winter
159 2009 Winter
160 2008 Winter
161 2007 Winter
162 2006 Winter
163 2005 Winter
164 2004 Winter
165 2003 Winter
166 2002 Winter
167 2001 Winter
168 2000 Winter
169 1999 Winter
170 1998 Winter
171 1997 Winter
172 1996 Winter
173 1995 Winter
174 1994 Winter
175 1993 Winter
176 1992 Winter
177 1991 Winter
178 1990 Winter
179 1989 Winter
180 1988 Winter
181 1987 Winter
182 1986 Winter
183 1985 Winter
184 1984 Winter
185 1983 Winter
186 1982 Winter
187 1981 Winter
188 1980 Winter
189 1979 Winter
190 1978 Winter
191 1977 Winter
192 1976 Winter
193 1975 Winter
194 1974 Winter
195 1973 Winter
196 1972 Winter
197 1971 Winter
198 1970 Winter
199 1969 Winter
200 1968 Winter
201 1967 Winter
202 1966 Winter
203 1965 Winter
204 1964 Winter
205 1963 Winter
206 1962 Winter
207 1961 Winter
208 1960 Winter
209 1959 Winter
210 1958 Winter
211 1957 Winter
212 1956 Winter
213 1955 Winter
214 1954 Winter
215 1953 Winter
216 1952 Winter
217 1951 Winter
218 1950 Winter
219 1949 Winter
220 1948 Winter
221 1947 Winter
222 1946 Winter
223 1945 Winter
224 1944 Winter
225 1943 Winter
226 1942 Winter
227 1941 Winter
228 1940 Winter
229 1939 Winter
230 1938 Winter
231 2,018 Winter
232 2,018 Winter
233 2,018 Winter
234 2,018 Winter
235 2,018 Winter
236 2,018 Winter
237 2,018 Winter
238 2,018 Winter
239 2,018 Winter
240 2,018 Winter
241 2,018 Winter
242 2,018 Winter
243 2,018 Winter
244 2,018 Winter
245 2,018 Winter
246 2,018 Winter
247 2,018 Winter
248 2,018 Winter
249 2,018 Winter
250 2,018 Winter
251 2,018 Winter
252 2,018 Winter
253 2,018 Winter
254 2,018 Winter
255 2,018 Winter
256 2,018 Winter
257 2,018 Winter
258 2,018 Winter
259 2,017 Winter
260 2,017 Winter
261 2,017 Winter
262 2,017 Winter
263 2,017 Winter
264 2,017 Winter
265 2,017 Winter
266 2,017 Winter
267 2,017 Winter
268 2,017 Winter
269 2,017 Winter
270 2,017 Winter
271 2,017 Winter
272 2,017 Winter
273 2,017 Winter
274 2,017 Winter
275 2,017 Winter
276 2,017 Winter
277 2,017 Winter
278 2,017 Winter
279 2,017 Winter
280 2,017 Winter
281 2,017 Winter
282 2,017 Winter
283 2,017 Winter
284 2,017 Winter
285 2,017 Winter
286 2,017 Winter
287 2,016 Winter
288 2,016 Winter
289 2,016 Winter
290 2,016 Winter
291 2,016 Winter
292 2,016 Winter
293 2,016 Winter
294 2,016 Winter
295 2,016 Winter
296 2,016 Winter
297 2,016 Winter
298 2,016 Winter
299 2,016 Winter
300 2,016 Winter
301 2,016 Winter
302 2,016 Winter
303 2,016 Winter
304 2,016 Winter
305 2,016 Winter
306 2,016 Winter
307 2,016 Winter
308 2,016 Winter
309 2,016 Winter
310 2,016 Winter
311 2,016 Winter
312 2,016 Winter
313 2,016 Winter
314 2,016 Winter
315 2,016 Winter
316 2,015 Winter
317 2,015 Winter
318 2,015 Winter
319 2,015 Winter
320 2,015 Winter
321 2,015 Winter
322 2,015 Winter
323 2,015 Winter
324 2,015 Winter
325 2,015 Winter
326 2,015 Winter
327 2,015 Winter
328 2,015 Winter
329 2,015 Winter
330 2,015 Winter
331 2,015 Winter
332 2,015 Winter
333 2,015 Winter
334 2,015 Winter
335 2,015 Winter
336 2,015 Winter
337 2,015 Winter
338 2,015 Winter
339 2,015 Winter
340 2,015 Winter
341 2,015 Winter
342 2,015 Winter
343 2,015 Winter
344 2,014 Winter
345 2,014 Winter
346 2,014 Winter
347 2,014 Winter
348 2,014 Winter
349 2,014 Winter
350 2,014 Winter
351 2,014 Winter
352 2,014 Winter
353 2,014 Winter
354 2,014 Winter
355 2,014 Winter
356 2,014 Winter
357 2,014 Winter
358 2,014 Winter
359 2,014 Winter
360 2,014 Winter
361 2,014 Winter
362 2,014 Winter
363 2,014 Winter
364 2,014 Winter
365 2,014 Winter
366 2,014 Winter
367 2,014 Winter
368 2,014 Winter
369 2,014 Winter
370 2,014 Winter
371 2,014 Winter
372 2013 Winter
373 2012 Winter
374 2011 Winter
375 2010 Winter
376 2009 Winter
377 2008 Winter
378 2007 Winter
379 2006 Winter
380 2005 Winter
381 2004 Winter
382 2003 Winter
383 2002 Winter
384 2001 Winter
385 2000 Winter
386 1999 Winter
387 1998 Winter
388 1997 Winter
389 1996 Winter
390 1995 Winter
391 1994 Winter
392 1993 Winter
393 1992 Winter
394 1991 Winter
395 1990 Winter
396 1989 Winter
397 1988 Winter
398 1987 Winter
399 1986 Winter
400 1985 Winter
401 1984 Winter
402 1983 Winter
403 1982 Winter
404 1981 Winter
405 1980 Winter
406 1979 Winter
407 1978 Winter
408 1977 Winter
409 1976 Winter
410 1975 Winter
411 1974 Winter
412 1973 Winter
413 1972 Winter
414 1971 Winter
415 1970 Winter
416 1969 Winter
417 1968 Winter
418 1967 Winter
419 1966 Winter
420 1965 Winter
421 1964 Winter
422 1963 Winter
423 1962 Winter
424 1961 Winter
425 1960 Winter
426 1959 Winter
427 1958 Winter
428 1957 Winter
429 1956 Winter
430 1955 Winter
431 1954 Winter
432 1953 Winter
433 1952 Winter
434 1951 Winter
435 1950 Winter
436 1949 Winter
437 1948 Winter
438 1947 Winter
439 1946 Winter
440 1945 Winter
441 1944 Winter
442 1943 Winter
443 1942 Winter
444 1941 Winter
445 1940 Winter
446 1939 Winter
447 1938 Winter
448 2,018 Spring
449 2,018 Spring
450 2,018 Spring
451 2,018 Spring
452 2,018 Spring
453 2,018 Spring
454 2,018 Spring
455 2,018 Spring
456 2,018 Spring
457 2,018 Spring
458 2,018 Spring
459 2,018 Spring
460 2,018 Spring
461 2,018 Spring
462 2,018 Spring
463 2,018 Spring
464 2,018 Spring
465 2,018 Spring
466 2,018 Spring
467 2,018 Spring
468 2,018 Spring
469 2,018 Spring
470 2,018 Spring
471 2,018 Spring
472 2,018 Spring
473 2,018 Spring
474 2,018 Spring
475 2,018 Spring
476 2,018 Spring
477 2,018 Spring
478 2,018 Spring
479 2,017 Spring
480 2,017 Spring
481 2,017 Spring
482 2,017 Spring
483 2,017 Spring
484 2,017 Spring
485 2,017 Spring
486 2,017 Spring
487 2,017 Spring
488 2,017 Spring
489 2,017 Spring
490 2,017 Spring
491 2,017 Spring
492 2,017 Spring
493 2,017 Spring
494 2,017 Spring
495 2,017 Spring
496 2,017 Spring
497 2,017 Spring
498 2,017 Spring
499 2,017 Spring
500 2,017 Spring
501 2,017 Spring
502 2,017 Spring
503 2,017 Spring
504 2,017 Spring
505 2,017 Spring

506 2,017 Spring
507 2,017 Spring
508 2,017 Spring
509 2,017 Spring
510 2,016 Spring
511 2,016 Spring
512 2,016 Spring
513 2,016 Spring
514 2,016 Spring
515 2,016 Spring
516 2,016 Spring
517 2,016 Spring
518 2,016 Spring
519 2,016 Spring
520 2,016 Spring
521 2,016 Spring
522 2,016 Spring
523 2,016 Spring
524 2,016 Spring
525 2,016 Spring
526 2,016 Spring
527 2,016 Spring
528 2,016 Spring
529 2,016 Spring
530 2,016 Spring
531 2,016 Spring
532 2,016 Spring
533 2,016 Spring
534 2,016 Spring
535 2,016 Spring
536 2,016 Spring
537 2,016 Spring
538 2,016 Spring
539 2,016 Spring
540 2,016 Spring
541 2,015 Spring
542 2,015 Spring
543 2,015 Spring
544 2,015 Spring
545 2,015 Spring
546 2,015 Spring
547 2,015 Spring
548 2,015 Spring
549 2,015 Spring
550 2,015 Spring
551 2,015 Spring
552 2,015 Spring
553 2,015 Spring
554 2,015 Spring
555 2,015 Spring
556 2,015 Spring
557 2,015 Spring
558 2,015 Spring
559 2,015 Spring
560 2,015 Spring
561 2,015 Spring
562 2,015 Spring
563 2,015 Spring
564 2,015 Spring
565 2,015 Spring
566 2,015 Spring
567 2,015 Spring
568 2,015 Spring
569 2,015 Spring
570 2,015 Spring
571 2,015 Spring
572 2,014 Spring
573 2,014 Spring
574 2,014 Spring
575 2,014 Spring
576 2,014 Spring
577 2,014 Spring
578 2,014 Spring
579 2,014 Spring
580 2,014 Spring
581 2,014 Spring
582 2,014 Spring
583 2,014 Spring
584 2,014 Spring
585 2,014 Spring
586 2,014 Spring
587 2,014 Spring
588 2,014 Spring
589 2,014 Spring
590 2,014 Spring
591 2,014 Spring
592 2,014 Spring
593 2,014 Spring
594 2,014 Spring
595 2,014 Spring
596 2,014 Spring
597 2,014 Spring
598 2,014 Spring
599 2,014 Spring
600 2,014 Spring
601 2,014 Spring
602 2,014 Spring
603 2013 Spring
604 2012 Spring
605 2011 Spring
606 2010 Spring
607 2009 Spring
608 2008 Spring
609 2007 Spring
610 2006 Spring
611 2005 Spring
612 2004 Spring
613 2003 Spring
614 2002 Spring
615 2001 Spring
616 2000 Spring
617 1999 Spring
618 1998 Spring
619 1997 Spring
620 1996 Spring
621 1995 Spring
622 1994 Spring
623 1993 Spring
624 1992 Spring
625 1991 Spring
626 1990 Spring
627 1989 Spring
628 1988 Spring
629 1987 Spring
630 1986 Spring
631 1985 Spring
632 1984 Spring
633 1983 Spring
634 1982 Spring
635 1981 Spring
636 1980 Spring
637 1979 Spring
638 1978 Spring
639 1977 Spring
640 1976 Spring
641 1975 Spring
642 1974 Spring
643 1973 Spring
644 1972 Spring
645 1971 Spring
646 1970 Spring
647 1969 Spring
648 1968 Spring
649 1967 Spring
650 1966 Spring
651 1965 Spring
652 1964 Spring
653 1963 Spring
654 1962 Spring
655 1961 Spring
656 1960 Spring
657 1959 Spring
658 1958 Spring
659 1957 Spring
660 1956 Spring
661 1955 Spring
662 1954 Spring
663 1953 Spring
664 1952 Spring
665 1951 Spring
666 1950 Spring
667 1949 Spring
668 1948 Spring
669 1947 Spring
670 1946 Spring
671 1945 Spring
672 1944 Spring
673 1943 Spring
674 1942 Spring
675 1941 Spring
676 1940 Spring
677 1939 Spring
678 1938 Spring
679 2,018 Spring
680 2,018 Spring
681 2,018 Spring
682 2,018 Spring
683 2,018 Spring
684 2,018 Spring
685 2,018 Spring
686 2,018 Spring
687 2,018 Spring
688 2,018 Spring
689 2,018 Spring
690 2,018 Spring
691 2,018 Spring
692 2,018 Spring
693 2,018 Spring
694 2,018 Spring
695 2,018 Spring
696 2,018 Spring
697 2,018 Spring
698 2,018 Spring
699 2,018 Spring
700 2,018 Spring
701 2,018 Spring
702 2,018 Spring
703 2,018 Spring
704 2,018 Spring
705 2,018 Spring
706 2,018 Spring
707 2,018 Spring
708 2,018 Spring
709 2,017 Spring
710 2,017 Spring
711 2,017 Spring
712 2,017 Spring
713 2,017 Spring
714 2,017 Spring
715 2,017 Spring
716 2,017 Spring
717 2,017 Spring
718 2,017 Spring
719 2,017 Spring
720 2,017 Spring
721 2,017 Spring
722 2,017 Spring
723 2,017 Spring
724 2,017 Spring
725 2,017 Spring
726 2,017 Spring
727 2,017 Spring
728 2,017 Spring
729 2,017 Spring
730 2,017 Spring
731 2,017 Spring
732 2,017 Spring
733 2,017 Spring
734 2,017 Spring
735 2,017 Spring
736 2,017 Spring
737 2,017 Spring
738 2,017 Spring
739 2,016 Spring
740 2,016 Spring
741 2,016 Spring
742 2,016 Spring
743 2,016 Spring
744 2,016 Spring
745 2,016 Spring
746 2,016 Spring
747 2,016 Spring
748 2,016 Spring
749 2,016 Spring
750 2,016 Spring
751 2,016 Spring
752 2,016 Spring
753 2,016 Spring
754 2,016 Spring
755 2,016 Spring
756 2,016 Spring
757 2,016 Spring
758 2,016 Spring
759 2,016 Spring
760 2,016 Spring
761 2,016 Spring
762 2,016 Spring
763 2,016 Spring
764 2,016 Spring
765 2,016 Spring
766 2,016 Spring
767 2,016 Spring
768 2,016 Spring
769 2,015 Spring
770 2,015 Spring
771 2,015 Spring
772 2,015 Spring
773 2,015 Spring
774 2,015 Spring
775 2,015 Spring
776 2,015 Spring
777 2,015 Spring
778 2,015 Spring
779 2,015 Spring
780 2,015 Spring
781 2,015 Spring
782 2,015 Spring
783 2,015 Spring
784 2,015 Spring
785 2,015 Spring
786 2,015 Spring
787 2,015 Spring
788 2,015 Spring
789 2,015 Spring
790 2,015 Spring
791 2,015 Spring
792 2,015 Spring
793 2,015 Spring
794 2,015 Spring
795 2,015 Spring
796 2,015 Spring
797 2,015 Spring
798 2,015 Spring
799 2,014 Spring
800 2,014 Spring
801 2,014 Spring
802 2,014 Spring
803 2,014 Spring
804 2,014 Spring
805 2,014 Spring
806 2,014 Spring
807 2,014 Spring
808 2,014 Spring
809 2,014 Spring
810 2,014 Spring
811 2,014 Spring
812 2,014 Spring
813 2,014 Spring
814 2,014 Spring
815 2,014 Spring
816 2,014 Spring
817 2,014 Spring
818 2,014 Spring
819 2,014 Spring
820 2,014 Spring
821 2,014 Spring
822 2,014 Spring
823 2,014 Spring
824 2,014 Spring
825 2,014 Spring
826 2,014 Spring
827 2,014 Spring
828 2,014 Spring
829 2013 Spring
830 2012 Spring
831 2011 Spring
832 2010 Spring
833 2009 Spring
834 2008 Spring
835 2007 Spring
836 2006 Spring
837 2005 Spring
838 2004 Spring
839 2003 Spring
840 2002 Spring
841 2001 Spring
842 2000 Spring
843 1999 Spring
844 1998 Spring
845 1997 Spring
846 1996 Spring
847 1995 Spring
848 1994 Spring
849 1993 Spring
850 1992 Spring
851 1991 Spring
852 1990 Spring
853 1989 Spring
854 1988 Spring
855 1987 Spring
856 1986 Spring
857 1985 Spring
858 1984 Spring
859 1983 Spring
860 1982 Spring
861 1981 Spring
862 1980 Spring
863 1979 Spring
864 1978 Spring
865 1977 Spring
866 1976 Spring
867 1975 Spring
868 1974 Spring
869 1973 Spring
870 1972 Spring
871 1971 Spring
872 1970 Spring
873 1969 Spring
874 1968 Spring
875 1967 Spring
876 1966 Spring
877 1965 Spring
878 1964 Spring
879 1963 Spring
880 1962 Spring
881 1961 Spring
882 1960 Spring
883 1959 Spring
884 1958 Spring
885 1957 Spring
886 1956 Spring
887 1955 Spring
888 1954 Spring
889 1953 Spring
890 1952 Spring
891 1951 Spring
892 1950 Spring
893 1949 Spring
894 1948 Spring
895 1947 Spring
896 1946 Spring
897 1945 Spring
898 1944 Spring
899 1943 Spring
900 1942 Spring
901 1941 Spring
902 1940 Spring
903 1939 Spring
904 1938 Spring
905 2,018 Spring
906 2,018 Spring
907 2,018 Spring
908 2,018 Spring
909 2,018 Spring
910 2,018 Spring
911 2,018 Spring
912 2,018 Spring
913 2,018 Spring
914 2,018 Spring
915 2,018 Spring
916 2,018 Spring
917 2,018 Spring
918 2,018 Spring
919 2,018 Spring
920 2,018 Spring
921 2,018 Spring
922 2,018 Spring
923 2,018 Spring
924 2,018 Spring
925 2,018 Spring
926 2,018 Spring
927 2,018 Spring
928 2,018 Spring
929 2,018 Spring
930 2,018 Spring
931 2,018 Spring
932 2,018 Spring
933 2,018 Spring
934 2,018 Spring
935 2,018 Spring
936 2,017 Spring
937 2,017 Spring
938 2,017 Spring
939 2,017 Spring
940 2,017 Spring
941 2,017 Spring
942 2,017 Spring
943 2,017 Spring
944 2,017 Spring
945 2,017 Spring
946 2,017 Spring
947 2,017 Spring
948 2,017 Spring
949 2,017 Spring
950 2,017 Spring
951 2,017 Spring
952 2,017 Spring
953 2,017 Spring
954 2,017 Spring
955 2,017 Spring
956 2,017 Spring
957 2,017 Spring
958 2,017 Spring
959 2,017 Spring
960 2,017 Spring
961 2,017 Spring
962 2,017 Spring
963 2,017 Spring
964 2,017 Spring
965 2,017 Spring
966 2,017 Spring
967 2,016 Spring
968 2,016 Spring
969 2,016 Spring
970 2,016 Spring
971 2,016 Spring
972 2,016 Spring
973 2,016 Spring
974 2,016 Spring
975 2,016 Spring
976 2,016 Spring
977 2,016 Spring
978 2,016 Spring
979 2,016 Spring
980 2,016 Spring
981 2,016 Spring
982 2,016 Spring
983 2,016 Spring
984 2,016 Spring
985 2,016 Spring
986 2,016 Spring
987 2,016 Spring
988 2,016 Spring
989 2,016 Spring
990 2,016 Spring
991 2,016 Spring
992 2,016 Spring
993 2,016 Spring
994 2,016 Spring
995 2,016 Spring
996 2,016 Spring
997 2,016 Spring
998 2,015 Spring
999 2,015 Spring
1000 2,015 Spring
1001 2,015 Spring
1002 2,015 Spring
1003 2,015 Spring
1004 2,015 Spring
1005 2,015 Spring
1006 2,015 Spring
1007 2,015 Spring
1008 2,015 Spring
1009 2,015 Spring
1010 2,015 Spring
1011 2,015 Spring
1012 2,015 Spring
1013 2,015 Spring
1014 2,015 Spring
1015 2,015 Spring
1016 2,015 Spring
1017 2,015 Spring
1018 2,015 Spring
1019 2,015 Spring
1020 2,015 Spring
1021 2,015 Spring
1022 2,015 Spring
1023 2,015 Spring
1024 2,015 Spring
1025 2,015 Spring
1026 2,015 Spring
1027 2,015 Spring
1028 2,015 Spring
1029 2,014 Spring
1030 2,014 Spring
1031 2,014 Spring
1032 2,014 Spring
1033 2,014 Spring
1034 2,014 Spring
1035 2,014 Spring
1036 2,014 Spring
1037 2,014 Spring
1038 2,014 Spring
1039 2,014 Spring
1040 2,014 Spring
1041 2,014 Spring
1042 2,014 Spring
1043 2,014 Spring
1044 2,014 Spring
1045 2,014 Spring
1046 2,014 Spring
1047 2,014 Spring
1048 2,014 Spring
1049 2,014 Spring
1050 2,014 Spring
1051 2,014 Spring
1052 2,014 Spring
1053 2,014 Spring
1054 2,014 Spring
1055 2,014 Spring
1056 2,014 Spring
1057 2,014 Spring
1058 2,014 Spring
1059 2,014 Spring
1060 2013 Spring
1061 2012 Spring
1062 2011 Spring
1063 2010 Spring
1064 2009 Spring
1065 2008 Spring
1066 2007 Spring
1067 2006 Spring
1068 2005 Spring
1069 2004 Spring
1070 2003 Spring
1071 2002 Spring
1072 2001 Spring
1073 2000 Spring
1074 1999 Spring
1075 1998 Spring
1076 1997 Spring
1077 1996 Spring
1078 1995 Spring
1079 1994 Spring
1080 1993 Spring
1081 1992 Spring
1082 1991 Spring
1083 1990 Spring
1084 1989 Spring
1085 1988 Spring
1086 1987 Spring
1087 1986 Spring
1088 1985 Spring
1089 1984 Spring
1090 1983 Spring
1091 1982 Spring
1092 1981 Spring
1093 1980 Spring
1094 1979 Spring
1095 1978 Spring
1096 1977 Spring
1097 1976 Spring
1098 1975 Spring
1099 1974 Spring
1100 1973 Spring
1101 1972 Spring
1102 1971 Spring
1103 1970 Spring
1104 1969 Spring
1105 1968 Spring
1106 1967 Spring
1107 1966 Spring
1108 1965 Spring
1109 1964 Spring
1110 1963 Spring
1111 1962 Spring
1112 1961 Spring
1113 1960 Spring
1114 1959 Spring
1115 1958 Spring
1116 1957 Spring
1117 1956 Spring
1118 1955 Spring
1119 1954 Spring
1120 1953 Spring
1121 1952 Spring
1122 1951 Spring
1123 1950 Spring
1124 1949 Spring
1125 1948 Spring
1126 1947 Spring
1127 1946 Spring
1128 1945 Spring
1129 1944 Spring
1130 1943 Spring
1131 1942 Spring
1132 1941 Spring
1133 1940 Spring
1134 1939 Spring
1135 1938 Spring
1136 2,018 Summer
1137 2,018 Summer
1138 2,018 Summer
1139 2,018 Summer
1140 2,018 Summer
1141 2,018 Summer
1142 2,018 Summer
1143 2,018 Summer
1144 2,018 Summer
1145 2,018 Summer
1146 2,018 Summer
1147 2,018 Summer
1148 2,018 Summer
1149 2,018 Summer
1150 2,018 Summer
1151 2,018 Summer
1152 2,018 Summer
1153 2,018 Summer
1154 2,018 Summer
1155 2,018 Summer
1156 2,018 Summer
1157 2,018 Summer
1158 2,018 Summer
1159 2,018 Summer
1160 2,018 Summer
1161 2,018 Summer
1162 2,018 Summer
1163 2,018 Summer
1164 2,018 Summer
1165 2,018 Summer
1166 2,017 Summer
1167 2,017 Summer
1168 2,017 Summer
1169 2,017 Summer
1170 2,017 Summer
1171 2,017 Summer
1172 2,017 Summer
1173 2,017 Summer
1174 2,017 Summer
1175 2,017 Summer
1176 2,017 Summer
1177 2,017 Summer
1178 2,017 Summer
1179 2,017 Summer
1180 2,017 Summer
1181 2,017 Summer
1182 2,017 Summer
1183 2,017 Summer
1184 2,017 Summer
1185 2,017 Summer
1186 2,017 Summer
1187 2,017 Summer
1188 2,017 Summer
1189 2,017 Summer
1190 2,017 Summer
1191 2,017 Summer
1192 2,017 Summer
1193 2,017 Summer
1194 2,017 Summer
1195 2,017 Summer
1196 2,016 Summer
1197 2,016 Summer
1198 2,016 Summer
1199 2,016 Summer
1200 2,016 Summer
1201 2,016 Summer
1202 2,016 Summer
1203 2,016 Summer
1204 2,016 Summer
1205 2,016 Summer
1206 2,016 Summer
1207 2,016 Summer
1208 2,016 Summer
1209 2,016 Summer
1210 2,016 Summer
1211 2,016 Summer
1212 2,016 Summer
1213 2,016 Summer
1214 2,016 Summer
1215 2,016 Summer
1216 2,016 Summer
1217 2,016 Summer
1218 2,016 Summer
1219 2,016 Summer
1220 2,016 Summer
1221 2,016 Summer
1222 2,016 Summer
1223 2,016 Summer
1224 2,016 Summer
1225 2,016 Summer
1226 2,015 Summer
1227 2,015 Summer
1228 2,015 Summer
1229 2,015 Summer
1230 2,015 Summer
1231 2,015 Summer
1232 2,015 Summer
1233 2,015 Summer
1234 2,015 Summer
1235 2,015 Summer
1236 2,015 Summer
1237 2,015 Summer
1238 2,015 Summer
1239 2,015 Summer
1240 2,015 Summer
1241 2,015 Summer
1242 2,015 Summer
1243 2,015 Summer
1244 2,015 Summer
1245 2,015 Summer
1246 2,015 Summer
1247 2,015 Summer
1248 2,015 Summer
1249 2,015 Summer
1250 2,015 Summer
1251 2,015 Summer
1252 2,015 Summer
1253 2,015 Summer
1254 2,015 Summer
1255 2,015 Summer
1256 2,014 Summer
1257 2,014 Summer
1258 2,014 Summer
1259 2,014 Summer
1260 2,014 Summer
1261 2,014 Summer
1262 2,014 Summer
1263 2,014 Summer
1264 2,014 Summer
1265 2,014 Summer
1266 2,014 Summer
1267 2,014 Summer
1268 2,014 Summer
1269 2,014 Summer
1270 2,014 Summer
1271 2,014 Summer
1272 2,014 Summer
1273 2,014 Summer
1274 2,014 Summer
1275 2,014 Summer
1276 2,014 Summer
1277 2,014 Summer
1278 2,014 Summer
1279 2,014 Summer
1280 2,014 Summer
1281 2,014 Summer
1282 2,014 Summer
1283 2,014 Summer
1284 2,014 Summer
1285 2,014 Summer
1286 2,013 Summer
1287 2,013 Summer
1288 2,013 Summer
1289 2,013 Summer
1290 2,013 Summer
1291 2,013 Summer
1292 2,013 Summer
1293 2,013 Summer
1294 2,013 Summer
1295 2,013 Summer
1296 2,013 Summer
1297 2,013 Summer

1298 2,013 Summer
1299 2,013 Summer
1300 2,013 Summer
1301 2,013 Summer
1302 2,013 Summer
1303 2,013 Summer
1304 2013 Summer
1305 2012 Summer
1306 2011 Summer
1307 2010 Summer
1308 2009 Summer
1309 2008 Summer
1310 2007 Summer
1311 2006 Summer
1312 2005 Summer
1313 2004 Summer
1314 2003 Summer
1315 2002 Summer
1316 2001 Summer
1317 2000 Summer
1318 1999 Summer
1319 1998 Summer
1320 1997 Summer
1321 1996 Summer
1322 1995 Summer
1323 1994 Summer
1324 1993 Summer
1325 1992 Summer
1326 1991 Summer
1327 1990 Summer
1328 1989 Summer
1329 1988 Summer
1330 1987 Summer
1331 1986 Summer
1332 1985 Summer
1333 1984 Summer
1334 1983 Summer
1335 1982 Summer
1336 1981 Summer
1337 1980 Summer
1338 1979 Summer
1339 1978 Summer
1340 1977 Summer
1341 1976 Summer
1342 1975 Summer
1343 1974 Summer
1344 1973 Summer
1345 1972 Summer
1346 1971 Summer
1347 1970 Summer
1348 1969 Summer
1349 1968 Summer
1350 1967 Summer
1351 1966 Summer
1352 1965 Summer
1353 1964 Summer
1354 1963 Summer
1355 1962 Summer
1356 1961 Summer
1357 1960 Summer
1358 1959 Summer
1359 1958 Summer
1360 1957 Summer
1361 1956 Summer
1362 1955 Summer
1363 1954 Summer
1364 1953 Summer
1365 1952 Summer
1366 1951 Summer
1367 1950 Summer
1368 1949 Summer
1369 1948 Summer
1370 1947 Summer
1371 1946 Summer
1372 1945 Summer
1373 1944 Summer
1374 1943 Summer
1375 1942 Summer
1376 1941 Summer
1377 1940 Summer
1378 1939 Summer
1379 1938 Summer
1380 2,018 Summer
1381 2,018 Summer
1382 2,018 Summer
1383 2,018 Summer
1384 2,018 Summer
1385 2,018 Summer
1386 2,018 Summer
1387 2,018 Summer
1388 2,018 Summer
1389 2,018 Summer
1390 2,018 Summer
1391 2,018 Summer
1392 2,018 Summer
1393 2,018 Summer
1394 2,018 Summer
1395 2,018 Summer
1396 2,018 Summer
1397 2,018 Summer
1398 2,018 Summer
1399 2,018 Summer
1400 2,018 Summer
1401 2,018 Summer
1402 2,018 Summer
1403 2,018 Summer
1404 2,018 Summer
1405 2,018 Summer
1406 2,018 Summer
1407 2,018 Summer
1408 2,018 Summer
1409 2,018 Summer
1410 2,018 Summer
1411 2,017 Summer
1412 2,017 Summer
1413 2,017 Summer
1414 2,017 Summer
1415 2,017 Summer
1416 2,017 Summer
1417 2,017 Summer
1418 2,017 Summer
1419 2,017 Summer
1420 2,017 Summer
1421 2,017 Summer
1422 2,017 Summer
1423 2,017 Summer
1424 2,017 Summer
1425 2,017 Summer
1426 2,017 Summer
1427 2,017 Summer
1428 2,017 Summer
1429 2,017 Summer
1430 2,017 Summer
1431 2,017 Summer
1432 2,017 Summer
1433 2,017 Summer
1434 2,017 Summer
1435 2,017 Summer
1436 2,017 Summer
1437 2,017 Summer
1438 2,017 Summer
1439 2,017 Summer
1440 2,017 Summer
1441 2,017 Summer
1442 2,016 Summer
1443 2,016 Summer
1444 2,016 Summer
1445 2,016 Summer
1446 2,016 Summer
1447 2,016 Summer
1448 2,016 Summer
1449 2,016 Summer
1450 2,016 Summer
1451 2,016 Summer
1452 2,016 Summer
1453 2,016 Summer
1454 2,016 Summer
1455 2,016 Summer
1456 2,016 Summer
1457 2,016 Summer
1458 2,016 Summer
1459 2,016 Summer
1460 2,016 Summer
1461 2,016 Summer
1462 2,016 Summer
1463 2,016 Summer
1464 2,016 Summer
1465 2,016 Summer
1466 2,016 Summer
1467 2,016 Summer
1468 2,016 Summer
1469 2,016 Summer
1470 2,016 Summer
1471 2,016 Summer
1472 2,016 Summer
1473 2,015 Summer
1474 2,015 Summer
1475 2,015 Summer
1476 2,015 Summer
1477 2,015 Summer
1478 2,015 Summer
1479 2,015 Summer
1480 2,015 Summer
1481 2,015 Summer
1482 2,015 Summer
1483 2,015 Summer
1484 2,015 Summer
1485 2,015 Summer
1486 2,015 Summer
1487 2,015 Summer
1488 2,015 Summer
1489 2,015 Summer
1490 2,015 Summer
1491 2,015 Summer
1492 2,015 Summer
1493 2,015 Summer
1494 2,015 Summer
1495 2,015 Summer
1496 2,015 Summer
1497 2,015 Summer
1498 2,015 Summer
1499 2,015 Summer
1500 2,015 Summer
1501 2,015 Summer
1502 2,015 Summer
1503 2,015 Summer
1504 2,014 Summer
1505 2,014 Summer
1506 2,014 Summer
1507 2,014 Summer
1508 2,014 Summer
1509 2,014 Summer
1510 2,014 Summer
1511 2,014 Summer
1512 2,014 Summer
1513 2,014 Summer
1514 2,014 Summer
1515 2,014 Summer
1516 2,014 Summer
1517 2,014 Summer
1518 2,014 Summer
1519 2,014 Summer
1520 2,014 Summer
1521 2,014 Summer
1522 2,014 Summer
1523 2,014 Summer
1524 2,014 Summer
1525 2,014 Summer
1526 2,014 Summer
1527 2,014 Summer
1528 2,014 Summer
1529 2,014 Summer
1530 2,014 Summer
1531 2,014 Summer
1532 2,014 Summer
1533 2,014 Summer
1534 2,014 Summer
1535 2,013 Summer
1536 2,013 Summer
1537 2,013 Summer
1538 2,013 Summer
1539 2,013 Summer
1540 2,013 Summer
1541 2,013 Summer
1542 2,013 Summer
1543 2,013 Summer
1544 2,013 Summer
1545 2,013 Summer
1546 2,013 Summer
1547 2,013 Summer
1548 2,013 Summer
1549 2,013 Summer
1550 2,013 Summer
1551 2,013 Summer
1552 2,013 Summer
1553 2,013 Summer
1554 2,013 Summer
1555 2,013 Summer
1556 2,013 Summer
1557 2,013 Summer
1558 2,013 Summer
1559 2,013 Summer
1560 2,013 Summer
1561 2,013 Summer
1562 2,013 Summer
1563 2,013 Summer
1564 2,013 Summer
1565 2,013 Summer
1566 2012 Summer
1567 2011 Summer
1568 2010 Summer
1569 2009 Summer
1570 2008 Summer
1571 2007 Summer
1572 2006 Summer
1573 2005 Summer
1574 2004 Summer
1575 2003 Summer
1576 2002 Summer
1577 2001 Summer
1578 2000 Summer
1579 1999 Summer
1580 1998 Summer
1581 1997 Summer
1582 1996 Summer
1583 1995 Summer
1584 1994 Summer
1585 1993 Summer
1586 1992 Summer
1587 1991 Summer
1588 1990 Summer
1589 1989 Summer
1590 1988 Summer
1591 1987 Summer
1592 1986 Summer
1593 1985 Summer
1594 1984 Summer
1595 1983 Summer
1596 1982 Summer
1597 1981 Summer
1598 1980 Summer
1599 1979 Summer
1600 1978 Summer
1601 1977 Summer
1602 1976 Summer
1603 1975 Summer
1604 1974 Summer
1605 1973 Summer
1606 1972 Summer
1607 1971 Summer
1608 1970 Summer
1609 1969 Summer
1610 1968 Summer
1611 1967 Summer
1612 1966 Summer
1613 1965 Summer
1614 1964 Summer
1615 1963 Summer
1616 1962 Summer
1617 1961 Summer
1618 1960 Summer
1619 1959 Summer
1620 1958 Summer
1621 1957 Summer
1622 1956 Summer
1623 1955 Summer
1624 1954 Summer
1625 1953 Summer
1626 1952 Summer
1627 1951 Summer
1628 1950 Summer
1629 1949 Summer
1630 1948 Summer
1631 1947 Summer
1632 1946 Summer
1633 1945 Summer
1634 1944 Summer
1635 1943 Summer
1636 1942 Summer
1637 1941 Summer
1638 1940 Summer
1639 1939 Summer
1640 1938 Summer
1641 2,018 Summer
1642 2,018 Summer
1643 2,018 Summer
1644 2,018 Summer
1645 2,018 Summer
1646 2,018 Summer
1647 2,018 Summer
1648 2,018 Summer
1649 2,018 Summer
1650 2,018 Summer
1651 2,018 Summer
1652 2,018 Summer
1653 2,018 Summer
1654 2,018 Summer
1655 2,018 Summer
1656 2,018 Summer
1657 2,018 Summer
1658 2,018 Summer
1659 2,018 Summer
1660 2,018 Summer
1661 2,018 Summer
1662 2,018 Summer
1663 2,018 Summer
1664 2,018 Summer
1665 2,018 Summer
1666 2,018 Summer
1667 2,018 Summer
1668 2,018 Summer
1669 2,018 Summer
1670 2,018 Summer
1671 2,018 Summer
1672 2,017 Summer
1673 2,017 Summer
1674 2,017 Summer
1675 2,017 Summer
1676 2,017 Summer
1677 2,017 Summer
1678 2,017 Summer
1679 2,017 Summer
1680 2,017 Summer
1681 2,017 Summer
1682 2,017 Summer
1683 2,017 Summer
1684 2,017 Summer
1685 2,017 Summer
1686 2,017 Summer
1687 2,017 Summer
1688 2,017 Summer
1689 2,017 Summer
1690 2,017 Summer
1691 2,017 Summer
1692 2,017 Summer
1693 2,017 Summer
1694 2,017 Summer
1695 2,017 Summer
1696 2,017 Summer
1697 2,017 Summer
1698 2,017 Summer
1699 2,017 Summer
1700 2,017 Summer
1701 2,017 Summer
1702 2,017 Summer
1703 2,016 Summer
1704 2,016 Summer
1705 2,016 Summer
1706 2,016 Summer
1707 2,016 Summer
1708 2,016 Summer
1709 2,016 Summer
1710 2,016 Summer
1711 2,016 Summer
1712 2,016 Summer
1713 2,016 Summer
1714 2,016 Summer
1715 2,016 Summer
1716 2,016 Summer
1717 2,016 Summer
1718 2,016 Summer
1719 2,016 Summer
1720 2,016 Summer
1721 2,016 Summer
1722 2,016 Summer
1723 2,016 Summer
1724 2,016 Summer
1725 2,016 Summer
1726 2,016 Summer
1727 2,016 Summer
1728 2,016 Summer
1729 2,016 Summer
1730 2,016 Summer
1731 2,016 Summer
1732 2,016 Summer
1733 2,016 Summer
1734 2,015 Summer
1735 2,015 Summer
1736 2,015 Summer
1737 2,015 Summer
1738 2,015 Summer
1739 2,015 Summer
1740 2,015 Summer
1741 2,015 Summer
1742 2,015 Summer
1743 2,015 Summer
1744 2,015 Summer
1745 2,015 Summer
1746 2,015 Summer
1747 2,015 Summer
1748 2,015 Summer
1749 2,015 Summer
1750 2,015 Summer
1751 2,015 Summer
1752 2,015 Summer
1753 2,015 Summer
1754 2,015 Summer
1755 2,015 Summer
1756 2,015 Summer
1757 2,015 Summer
1758 2,015 Summer
1759 2,015 Summer
1760 2,015 Summer
1761 2,015 Summer
1762 2,015 Summer
1763 2,015 Summer
1764 2,015 Summer
1765 2,014 Summer
1766 2,014 Summer
1767 2,014 Summer
1768 2,014 Summer
1769 2,014 Summer
1770 2,014 Summer
1771 2,014 Summer
1772 2,014 Summer
1773 2,014 Summer
1774 2,014 Summer
1775 2,014 Summer
1776 2,014 Summer
1777 2,014 Summer
1778 2,014 Summer
1779 2,014 Summer
1780 2,014 Summer
1781 2,014 Summer
1782 2,014 Summer
1783 2,014 Summer
1784 2,014 Summer
1785 2,014 Summer
1786 2,014 Summer
1787 2,014 Summer
1788 2,014 Summer
1789 2,014 Summer
1790 2,014 Summer
1791 2,014 Summer
1792 2,014 Summer
1793 2,014 Summer
1794 2,014 Summer
1795 2,014 Summer
1796 2,013 Summer
1797 2,013 Summer
1798 2,013 Summer
1799 2,013 Summer
1800 2,013 Summer
1801 2,013 Summer
1802 2,013 Summer
1803 2,013 Summer

1804 2,013 Summer
1805 2,013 Summer
1806 2,013 Summer
1807 2,013 Summer
1808 2,013 Summer
1809 2,013 Summer
1810 2,013 Summer
1811 2,013 Summer
1812 2,013 Summer
1813 2,013 Summer
1814 2,013 Summer
1815 2,013 Summer
1816 2,013 Summer
1817 2,013 Summer
1818 2,013 Summer
1819 2,013 Summer
1820 2,013 Summer
1821 2,013 Summer
1822 2,013 Summer
1823 2,013 Summer
1824 2,013 Summer
1825 2,013 Summer
1826 2,013 Summer
1827 2012 Summer
1828 2011 Summer
1829 2010 Summer
1830 2009 Summer
1831 2008 Summer
1832 2007 Summer
1833 2006 Summer
1834 2005 Summer
1835 2004 Summer
1836 2003 Summer
1837 2002 Summer
1838 2001 Summer
1839 2000 Summer
1840 1999 Summer
1841 1998 Summer
1842 1997 Summer
1843 1996 Summer
1844 1995 Summer
1845 1994 Summer
1846 1993 Summer
1847 1992 Summer
1848 1991 Summer
1849 1990 Summer
1850 1989 Summer
1851 1988 Summer
1852 1987 Summer
1853 1986 Summer
1854 1985 Summer
1855 1984 Summer
1856 1983 Summer
1857 1982 Summer
1858 1981 Summer
1859 1980 Summer
1860 1979 Summer
1861 1978 Summer
1862 1977 Summer
1863 1976 Summer
1864 1975 Summer
1865 1974 Summer
1866 1973 Summer
1867 1972 Summer
1868 1971 Summer
1869 1970 Summer
1870 1969 Summer
1871 1968 Summer
1872 1967 Summer
1873 1966 Summer
1874 1965 Summer
1875 1964 Summer
1876 1963 Summer
1877 1962 Summer
1878 1961 Summer
1879 1960 Summer
1880 1959 Summer
1881 1958 Summer
1882 1957 Summer
1883 1956 Summer
1884 1955 Summer
1885 1954 Summer
1886 1953 Summer
1887 1952 Summer
1888 1951 Summer
1889 1950 Summer
1890 1949 Summer
1891 1948 Summer
1892 1947 Summer
1893 1946 Summer
1894 1945 Summer
1895 1944 Summer
1896 1943 Summer
1897 1942 Summer
1898 1941 Summer
1899 1940 Summer
1900 1939 Summer
1901 1938 Summer
1902 2,018 Fall
1903 2,018 Fall
1904 2,018 Fall
1905 2,018 Fall
1906 2,018 Fall
1907 2,018 Fall
1908 2,018 Fall
1909 2,018 Fall
1910 2,018 Fall
1911 2,018 Fall
1912 2,018 Fall
1913 2,018 Fall
1914 2,018 Fall
1915 2,018 Fall
1916 2,018 Fall
1917 2,018 Fall
1918 2,018 Fall
1919 2,018 Fall
1920 2,018 Fall
1921 2,018 Fall
1922 2,018 Fall
1923 2,018 Fall
1924 2,018 Fall
1925 2,018 Fall
1926 2,018 Fall
1927 2,018 Fall
1928 2,018 Fall
1929 2,018 Fall
1930 2,018 Fall
1931 2,018 Fall
1932 2,017 Fall
1933 2,017 Fall
1934 2,017 Fall
1935 2,017 Fall
1936 2,017 Fall
1937 2,017 Fall
1938 2,017 Fall
1939 2,017 Fall
1940 2,017 Fall
1941 2,017 Fall
1942 2,017 Fall
1943 2,017 Fall
1944 2,017 Fall
1945 2,017 Fall
1946 2,017 Fall
1947 2,017 Fall
1948 2,017 Fall
1949 2,017 Fall
1950 2,017 Fall
1951 2,017 Fall
1952 2,017 Fall
1953 2,017 Fall
1954 2,017 Fall
1955 2,017 Fall
1956 2,017 Fall
1957 2,017 Fall
1958 2,017 Fall
1959 2,017 Fall
1960 2,017 Fall
1961 2,017 Fall
1962 2,016 Fall
1963 2,016 Fall
1964 2,016 Fall
1965 2,016 Fall
1966 2,016 Fall
1967 2,016 Fall
1968 2,016 Fall
1969 2,016 Fall
1970 2,016 Fall
1971 2,016 Fall
1972 2,016 Fall
1973 2,016 Fall
1974 2,016 Fall
1975 2,016 Fall
1976 2,016 Fall
1977 2,016 Fall
1978 2,016 Fall
1979 2,016 Fall
1980 2,016 Fall
1981 2,016 Fall
1982 2,016 Fall
1983 2,016 Fall
1984 2,016 Fall
1985 2,016 Fall
1986 2,016 Fall
1987 2,016 Fall
1988 2,016 Fall
1989 2,016 Fall
1990 2,016 Fall
1991 2,016 Fall
1992 2,015 Fall
1993 2,015 Fall
1994 2,015 Fall
1995 2,015 Fall
1996 2,015 Fall
1997 2,015 Fall
1998 2,015 Fall
1999 2,015 Fall
2000 2,015 Fall
2001 2,015 Fall
2002 2,015 Fall
2003 2,015 Fall
2004 2,015 Fall
2005 2,015 Fall
2006 2,015 Fall
2007 2,015 Fall
2008 2,015 Fall
2009 2,015 Fall
2010 2,015 Fall
2011 2,015 Fall
2012 2,015 Fall
2013 2,015 Fall
2014 2,015 Fall
2015 2,015 Fall
2016 2,015 Fall
2017 2,015 Fall
2018 2,015 Fall
2019 2,015 Fall
2020 2,015 Fall
2021 2,015 Fall
2022 2,014 Fall
2023 2,014 Fall
2024 2,014 Fall
2025 2,014 Fall
2026 2,014 Fall
2027 2,014 Fall
2028 2,014 Fall
2029 2,014 Fall
2030 2,014 Fall
2031 2,014 Fall
2032 2,014 Fall
2033 2,014 Fall
2034 2,014 Fall
2035 2,014 Fall
2036 2,014 Fall
2037 2,014 Fall
2038 2,014 Fall
2039 2,014 Fall
2040 2,014 Fall
2041 2,014 Fall
2042 2,014 Fall
2043 2,014 Fall
2044 2,014 Fall
2045 2,014 Fall
2046 2,014 Fall
2047 2,014 Fall
2048 2,014 Fall
2049 2,014 Fall
2050 2,014 Fall
2051 2,014 Fall
2052 2,013 Fall
2053 2,013 Fall
2054 2,013 Fall
2055 2,013 Fall
2056 2,013 Fall
2057 2,013 Fall
2058 2,013 Fall
2059 2,013 Fall
2060 2,013 Fall
2061 2,013 Fall
2062 2,013 Fall
2063 2,013 Fall
2064 2,013 Fall
2065 2,013 Fall
2066 2,013 Fall
2067 2,013 Fall
2068 2,013 Fall
2069 2,013 Fall
2070 2,013 Fall
2071 2,013 Fall
2072 2,013 Fall
2073 2,013 Fall
2074 2,013 Fall
2075 2,013 Fall
2076 2,013 Fall
2077 2,013 Fall
2078 2,013 Fall
2079 2,013 Fall
2080 2,013 Fall
2081 2,013 Fall
2082 2012 Fall
2083 2011 Fall
2084 2010 Fall
2085 2009 Fall
2086 2008 Fall
2087 2007 Fall
2088 2006 Fall
2089 2005 Fall
2090 2004 Fall
2091 2003 Fall
2092 2002 Fall
2093 2001 Fall
2094 2000 Fall
2095 1999 Fall
2096 1998 Fall
2097 1997 Fall
2098 1996 Fall
2099 1995 Fall
2100 1994 Fall
2101 1993 Fall
2102 1992 Fall
2103 1991 Fall
2104 1990 Fall
2105 1989 Fall
2106 1988 Fall
2107 1987 Fall
2108 1986 Fall
2109 1985 Fall
2110 1984 Fall
2111 1983 Fall
2112 1982 Fall
2113 1981 Fall
2114 1980 Fall
2115 1979 Fall
2116 1978 Fall
2117 1977 Fall
2118 1976 Fall
2119 1975 Fall
2120 1974 Fall
2121 1973 Fall
2122 1972 Fall
2123 1971 Fall
2124 1970 Fall
2125 1969 Fall
2126 1968 Fall
2127 1967 Fall
2128 1966 Fall
2129 1965 Fall
2130 1964 Fall
2131 1963 Fall
2132 1962 Fall
2133 1961 Fall
2134 1960 Fall
2135 1959 Fall
2136 1958 Fall
2137 1957 Fall
2138 1956 Fall
2139 1955 Fall
2140 1954 Fall
2141 1953 Fall
2142 1952 Fall
2143 1951 Fall
2144 1950 Fall
2145 1949 Fall
2146 1948 Fall
2147 1947 Fall
2148 1946 Fall
2149 1945 Fall
2150 1944 Fall
2151 1943 Fall
2152 1942 Fall
2153 1941 Fall
2154 1940 Fall
2155 1939 Fall
2156 1938 Fall
2157 2,018 Fall
2158 2,018 Fall
2159 2,018 Fall
2160 2,018 Fall
2161 2,018 Fall
2162 2,018 Fall
2163 2,018 Fall
2164 2,018 Fall
2165 2,018 Fall
2166 2,018 Fall
2167 2,018 Fall
2168 2,018 Fall
2169 2,018 Fall
2170 2,018 Fall
2171 2,018 Fall
2172 2,018 Fall
2173 2,018 Fall
2174 2,018 Fall
2175 2,018 Fall
2176 2,018 Fall
2177 2,018 Fall
2178 2,018 Fall
2179 2,018 Fall
2180 2,018 Fall
2181 2,018 Fall
2182 2,018 Fall
2183 2,018 Fall
2184 2,018 Fall
2185 2,018 Fall
2186 2,018 Fall
2187 2,018 Fall
2188 2,017 Fall
2189 2,017 Fall
2190 2,017 Fall
2191 2,017 Fall
2192 2,017 Fall
2193 2,017 Fall
2194 2,017 Fall
2195 2,017 Fall
2196 2,017 Fall
2197 2,017 Fall
2198 2,017 Fall
2199 2,017 Fall
2200 2,017 Fall
2201 2,017 Fall
2202 2,017 Fall
2203 2,017 Fall
2204 2,017 Fall
2205 2,017 Fall
2206 2,017 Fall
2207 2,017 Fall
2208 2,017 Fall
2209 2,017 Fall
2210 2,017 Fall
2211 2,017 Fall
2212 2,017 Fall
2213 2,017 Fall
2214 2,017 Fall
2215 2,017 Fall
2216 2,017 Fall
2217 2,017 Fall
2218 2,017 Fall
2219 2,016 Fall
2220 2,016 Fall
2221 2,016 Fall
2222 2,016 Fall
2223 2,016 Fall
2224 2,016 Fall
2225 2,016 Fall
2226 2,016 Fall
2227 2,016 Fall
2228 2,016 Fall
2229 2,016 Fall
2230 2,016 Fall
2231 2,016 Fall
2232 2,016 Fall
2233 2,016 Fall
2234 2,016 Fall
2235 2,016 Fall
2236 2,016 Fall
2237 2,016 Fall
2238 2,016 Fall
2239 2,016 Fall
2240 2,016 Fall
2241 2,016 Fall
2242 2,016 Fall
2243 2,016 Fall
2244 2,016 Fall
2245 2,016 Fall
2246 2,016 Fall
2247 2,016 Fall
2248 2,016 Fall
2249 2,016 Fall
2250 2,015 Fall
2251 2,015 Fall
2252 2,015 Fall
2253 2,015 Fall
2254 2,015 Fall
2255 2,015 Fall
2256 2,015 Fall
2257 2,015 Fall
2258 2,015 Fall
2259 2,015 Fall
2260 2,015 Fall
2261 2,015 Fall
2262 2,015 Fall
2263 2,015 Fall
2264 2,015 Fall
2265 2,015 Fall
2266 2,015 Fall
2267 2,015 Fall
2268 2,015 Fall
2269 2,015 Fall
2270 2,015 Fall
2271 2,015 Fall
2272 2,015 Fall
2273 2,015 Fall
2274 2,015 Fall
2275 2,015 Fall
2276 2,015 Fall
2277 2,015 Fall
2278 2,015 Fall
2279 2,015 Fall
2280 2,015 Fall
2281 2,014 Fall
2282 2,014 Fall
2283 2,014 Fall
2284 2,014 Fall
2285 2,014 Fall
2286 2,014 Fall
2287 2,014 Fall
2288 2,014 Fall
2289 2,014 Fall
2290 2,014 Fall
2291 2,014 Fall
2292 2,014 Fall
2293 2,014 Fall
2294 2,014 Fall
2295 2,014 Fall
2296 2,014 Fall
2297 2,014 Fall
2298 2,014 Fall
2299 2,014 Fall
2300 2,014 Fall
2301 2,014 Fall
2302 2,014 Fall
2303 2,014 Fall
2304 2,014 Fall
2305 2,014 Fall
2306 2,014 Fall
2307 2,014 Fall
2308 2,014 Fall
2309 2,014 Fall
2310 2,014 Fall
2311 2,014 Fall
2312 2,013 Fall
2313 2,013 Fall
2314 2,013 Fall
2315 2,013 Fall
2316 2,013 Fall
2317 2,013 Fall
2318 2,013 Fall
2319 2,013 Fall
2320 2,013 Fall

2321 2,013 Fall
2322 2,013 Fall
2323 2,013 Fall
2324 2,013 Fall
2325 2,013 Fall
2326 2,013 Fall
2327 2,013 Fall
2328 2,013 Fall
2329 2,013 Fall
2330 2,013 Fall
2331 2,013 Fall
2332 2,013 Fall
2333 2,013 Fall
2334 2,013 Fall
2335 2,013 Fall
2336 2,013 Fall
2337 2,013 Fall
2338 2,013 Fall
2339 2,013 Fall
2340 2,013 Fall
2341 2,013 Fall
2342 2,013 Fall
2343 2012 Fall
2344 2011 Fall
2345 2010 Fall
2346 2009 Fall
2347 2008 Fall
2348 2007 Fall
2349 2006 Fall
2350 2005 Fall
2351 2004 Fall
2352 2003 Fall
2353 2002 Fall
2354 2001 Fall
2355 2000 Fall
2356 1999 Fall
2357 1998 Fall
2358 1997 Fall
2359 1996 Fall
2360 1995 Fall
2361 1994 Fall
2362 1993 Fall
2363 1992 Fall
2364 1991 Fall
2365 1990 Fall
2366 1989 Fall
2367 1988 Fall
2368 1987 Fall
2369 1986 Fall
2370 1985 Fall
2371 1984 Fall
2372 1983 Fall
2373 1982 Fall
2374 1981 Fall
2375 1980 Fall
2376 1979 Fall
2377 1978 Fall
2378 1977 Fall
2379 1976 Fall
2380 1975 Fall
2381 1974 Fall
2382 1973 Fall
2383 1972 Fall
2384 1971 Fall
2385 1970 Fall
2386 1969 Fall
2387 1968 Fall
2388 1967 Fall
2389 1966 Fall
2390 1965 Fall
2391 1964 Fall
2392 1963 Fall
2393 1962 Fall
2394 1961 Fall
2395 1960 Fall
2396 1959 Fall
2397 1958 Fall
2398 1957 Fall
2399 1956 Fall
2400 1955 Fall
2401 1954 Fall
2402 1953 Fall
2403 1952 Fall
2404 1951 Fall
2405 1950 Fall
2406 1949 Fall
2407 1948 Fall
2408 1947 Fall
2409 1946 Fall
2410 1945 Fall
2411 1944 Fall
2412 1943 Fall
2413 1942 Fall
2414 1941 Fall
2415 1940 Fall
2416 1939 Fall
2417 1938 Fall
2418 2,018 Fall
2419 2,018 Fall
2420 2,018 Fall
2421 2,018 Fall
2422 2,018 Fall
2423 2,018 Fall
2424 2,018 Fall
2425 2,018 Fall
2426 2,018 Fall
2427 2,018 Fall
2428 2,018 Fall
2429 2,018 Fall
2430 2,018 Fall
2431 2,018 Fall
2432 2,017 Fall
2433 2,017 Fall
2434 2,017 Fall
2435 2,017 Fall
2436 2,017 Fall
2437 2,017 Fall
2438 2,017 Fall
2439 2,017 Fall
2440 2,017 Fall
2441 2,017 Fall
2442 2,017 Fall
2443 2,017 Fall
2444 2,017 Fall
2445 2,017 Fall
2446 2,017 Fall
2447 2,017 Fall
2448 2,017 Fall
2449 2,017 Fall
2450 2,017 Fall
2451 2,017 Fall
2452 2,017 Fall
2453 2,017 Fall
2454 2,017 Fall
2455 2,017 Fall
2456 2,017 Fall
2457 2,017 Fall
2458 2,017 Fall
2459 2,017 Fall
2460 2,017 Fall
2461 2,017 Fall
2462 2,016 Fall
2463 2,016 Fall
2464 2,016 Fall
2465 2,016 Fall
2466 2,016 Fall
2467 2,016 Fall
2468 2,016 Fall
2469 2,016 Fall
2470 2,016 Fall
2471 2,016 Fall
2472 2,016 Fall
2473 2,016 Fall
2474 2,016 Fall
2475 2,016 Fall
2476 2,016 Fall
2477 2,016 Fall
2478 2,016 Fall
2479 2,016 Fall
2480 2,016 Fall
2481 2,016 Fall
2482 2,016 Fall
2483 2,016 Fall
2484 2,016 Fall
2485 2,016 Fall
2486 2,016 Fall
2487 2,016 Fall
2488 2,016 Fall
2489 2,016 Fall
2490 2,016 Fall
2491 2,016 Fall
2492 2,015 Fall
2493 2,015 Fall
2494 2,015 Fall
2495 2,015 Fall
2496 2,015 Fall
2497 2,015 Fall
2498 2,015 Fall
2499 2,015 Fall
2500 2,015 Fall
2501 2,015 Fall
2502 2,015 Fall
2503 2,015 Fall
2504 2,015 Fall
2505 2,015 Fall
2506 2,015 Fall
2507 2,015 Fall
2508 2,015 Fall
2509 2,015 Fall
2510 2,015 Fall
2511 2,015 Fall
2512 2,015 Fall
2513 2,015 Fall
2514 2,015 Fall
2515 2,015 Fall
2516 2,015 Fall
2517 2,015 Fall
2518 2,015 Fall
2519 2,015 Fall
2520 2,015 Fall
2521 2,015 Fall
2522 2,014 Fall
2523 2,014 Fall
2524 2,014 Fall
2525 2,014 Fall
2526 2,014 Fall
2527 2,014 Fall
2528 2,014 Fall
2529 2,014 Fall
2530 2,014 Fall
2531 2,014 Fall
2532 2,014 Fall
2533 2,014 Fall
2534 2,014 Fall
2535 2,014 Fall
2536 2,014 Fall
2537 2,014 Fall
2538 2,014 Fall
2539 2,014 Fall
2540 2,014 Fall
2541 2,014 Fall
2542 2,014 Fall
2543 2,014 Fall
2544 2,014 Fall
2545 2,014 Fall
2546 2,014 Fall
2547 2,014 Fall
2548 2,014 Fall
2549 2,014 Fall
2550 2,014 Fall
2551 2,014 Fall
2552 2,013 Fall
2553 2,013 Fall
2554 2,013 Fall
2555 2,013 Fall
2556 2,013 Fall
2557 2,013 Fall
2558 2,013 Fall
2559 2,013 Fall
2560 2,013 Fall
2561 2,013 Fall
2562 2,013 Fall
2563 2,013 Fall
2564 2,013 Fall
2565 2,013 Fall
2566 2,013 Fall
2567 2,013 Fall
2568 2,013 Fall
2569 2,013 Fall
2570 2,013 Fall
2571 2,013 Fall
2572 2,013 Fall
2573 2,013 Fall
2574 2,013 Fall
2575 2,013 Fall
2576 2,013 Fall
2577 2,013 Fall
2578 2,013 Fall
2579 2,013 Fall
2580 2,013 Fall
2581 2,013 Fall
2582 2012 Fall
2583 2011 Fall
2584 2010 Fall
2585 2009 Fall
2586 2008 Fall
2587 2007 Fall
2588 2006 Fall
2589 2005 Fall
2590 2004 Fall
2591 2003 Fall
2592 2002 Fall
2593 2001 Fall
2594 2000 Fall
2595 1999 Fall
2596 1998 Fall
2597 1997 Fall
2598 1996 Fall
2599 1995 Fall
2600 1994 Fall
2601 1993 Fall
2602 1992 Fall
2603 1991 Fall
2604 1990 Fall
2605 1989 Fall
2606 1988 Fall
2607 1987 Fall
2608 1986 Fall
2609 1985 Fall
2610 1984 Fall
2611 1983 Fall
2612 1982 Fall
2613 1981 Fall
2614 1980 Fall
2615 1979 Fall
2616 1978 Fall
2617 1977 Fall
2618 1976 Fall
2619 1975 Fall
2620 1974 Fall
2621 1973 Fall
2622 1972 Fall
2623 1971 Fall
2624 1970 Fall
2625 1969 Fall
2626 1968 Fall
2627 1967 Fall
2628 1966 Fall
2629 1965 Fall
2630 1964 Fall
2631 1963 Fall
2632 1962 Fall
2633 1961 Fall
2634 1960 Fall
2635 1959 Fall
2636 1958 Fall
2637 1957 Fall
2638 1956 Fall
2639 1955 Fall
2640 1954 Fall
2641 1953 Fall
2642 1952 Fall
2643 1951 Fall
2644 1950 Fall
2645 1949 Fall
2646 1948 Fall
2647 1947 Fall
2648 1946 Fall
2649 1945 Fall
2650 1944 Fall
2651 1943 Fall
2652 1942 Fall
2653 1941 Fall
2654 1940 Fall
2655 1939 Fall
2656 1938 Fall
2657 1937 Fall
2658 2,017 Winter
2659 2,017 Winter
2660 2,017 Winter
2661 2,017 Winter
2662 2,017 Winter
2663 2,017 Winter
2664 2,017 Winter
2665 2,017 Winter
2666 2,017 Winter
2667 2,017 Winter
2668 2,017 Winter
2669 2,017 Winter
2670 2,017 Winter
2671 2,017 Winter
2672 2,017 Winter
2673 2,017 Winter
2674 2,017 Winter
2675 2,017 Winter
2676 2,017 Winter
2677 2,017 Winter
2678 2,017 Winter
2679 2,017 Winter
2680 2,017 Winter
2681 2,017 Winter
2682 2,017 Winter
2683 2,017 Winter
2684 2,017 Winter
2685 2,017 Winter
2686 2,017 Winter
2687 2,017 Winter
2688 2,017 Winter
2689 2,016 Winter
2690 2,016 Winter
2691 2,016 Winter
2692 2,016 Winter
2693 2,016 Winter
2694 2,016 Winter
2695 2,016 Winter
2696 2,016 Winter
2697 2,016 Winter
2698 2,016 Winter
2699 2,016 Winter
2700 2,016 Winter
2701 2,016 Winter
2702 2,016 Winter
2703 2,016 Winter
2704 2,016 Winter
2705 2,016 Winter
2706 2,016 Winter
2707 2,016 Winter
2708 2,016 Winter
2709 2,016 Winter
2710 2,016 Winter
2711 2,016 Winter
2712 2,016 Winter
2713 2,016 Winter
2714 2,016 Winter
2715 2,016 Winter
2716 2,016 Winter
2717 2,016 Winter
2718 2,016 Winter
2719 2,016 Winter
2720 2,015 Winter
2721 2,015 Winter
2722 2,015 Winter
2723 2,015 Winter
2724 2,015 Winter
2725 2,015 Winter
2726 2,015 Winter
2727 2,015 Winter
2728 2,015 Winter
2729 2,015 Winter
2730 2,015 Winter
2731 2,015 Winter
2732 2,015 Winter
2733 2,015 Winter
2734 2,015 Winter
2735 2,015 Winter
2736 2,015 Winter
2737 2,015 Winter
2738 2,015 Winter
2739 2,015 Winter
2740 2,015 Winter
2741 2,015 Winter
2742 2,015 Winter
2743 2,015 Winter
2744 2,015 Winter
2745 2,015 Winter
2746 2,015 Winter
2747 2,015 Winter
2748 2,015 Winter
2749 2,015 Winter
2750 2,015 Winter
2751 2,014 Winter
2752 2,014 Winter
2753 2,014 Winter
2754 2,014 Winter
2755 2,014 Winter
2756 2,014 Winter
2757 2,014 Winter
2758 2,014 Winter
2759 2,014 Winter
2760 2,014 Winter
2761 2,014 Winter
2762 2,014 Winter
2763 2,014 Winter
2764 2,014 Winter
2765 2,014 Winter
2766 2,014 Winter
2767 2,014 Winter
2768 2,014 Winter
2769 2,014 Winter
2770 2,014 Winter
2771 2,014 Winter
2772 2,014 Winter
2773 2,014 Winter
2774 2,014 Winter
2775 2,014 Winter
2776 2,014 Winter
2777 2,014 Winter
2778 2,014 Winter
2779 2,014 Winter
2780 2,014 Winter
2781 2,014 Winter
2782 2,013 Winter
2783 2,013 Winter
2784 2,013 Winter
2785 2,013 Winter
2786 2,013 Winter
2787 2,013 Winter
2788 2,013 Winter
2789 2,013 Winter
2790 2,013 Winter
2791 2,013 Winter
2792 2,013 Winter
2793 2,013 Winter
2794 2,013 Winter
2795 2,013 Winter
2796 2,013 Winter
2797 2,013 Winter
2798 2,013 Winter
2799 2,013 Winter
2800 2,013 Winter
2801 2,013 Winter
2802 2,013 Winter
2803 2,013 Winter
2804 2,013 Winter
2805 2,013 Winter
2806 2,013 Winter
2807 2,013 Winter
2808 2,013 Winter
2809 2,013 Winter
2810 2,013 Winter
2811 2,013 Winter
2812 2,013 Winter
2813 2012 Winter
2814 2011 Winter
2815 2010 Winter
2816 2009 Winter
2817 2008 Winter
2818 2007 Winter
2819 2006 Winter
2820 2005 Winter
2821 2004 Winter
2822 2003 Winter
2823 2002 Winter
2824 2001 Winter
2825 2000 Winter
2826 1999 Winter
2827 1998 Winter
2828 1997 Winter
2829 1996 Winter
2830 1995 Winter
2831 1994 Winter
2832 1993 Winter
2833 1992 Winter
2834 1991 Winter
2835 1990 Winter
2836 1989 Winter
2837 1988 Winter
2838 1987 Winter
2839 1986 Winter
2840 1985 Winter
2841 1984 Winter
2842 1983 Winter
2843 1982 Winter
2844 1981 Winter
2845 1980 Winter
2846 1979 Winter
2847 1978 Winter
2848 1977 Winter
2849 1976 Winter
2850 1975 Winter
2851 1974 Winter
2852 1973 Winter
2853 1972 Winter
2854 1971 Winter
2855 1970 Winter
2856 1969 Winter
2857 1968 Winter
2858 1967 Winter
2859 1966 Winter
2860 1965 Winter
2861 1964 Winter
2862 1963 Winter
2863 1962 Winter
2864 1961 Winter
2865 1960 Winter
2866 1959 Winter
2867 1958 Winter
2868 1957 Winter
2869 1956 Winter
2870 1955 Winter
2871 1954 Winter
2872 1953 Winter
2873 1952 Winter
2874 1951 Winter
2875 1950 Winter
2876 1949 Winter
2877 1948 Winter
2878 1947 Winter
2879 1946 Winter
2880 1945 Winter
2881 1944 Winter
2882 1943 Winter
2883 1942 Winter
2884 1941 Winter
2885 1940 Winter
2886 1939 Winter
2887 1938 Winter
2888 1937 Winter

In [24]:
#22
temp["Year"]= temp["Year"].str.replace(",", "") 
temp.head()

,Date,Year,Month,Mean Temp C,Max Temp C,Min Temp C,Rain mm,Snow cm,Precip,Season
0,31-Jan-18,2018,1,-7.0,2.0,-15.0,0.0,1.0,1.0,Winter
1,30-Jan-18,2018,1,-11.0,-7.0,-15.0,0.0,0.0,0.0,Winter
2,29-Jan-18,2018,1,-4.0,-2.0,-7.0,0.0,5.0,5.0,Winter
3,28-Jan-18,2018,1,1.0,5.0,-3.0,0.0,0.0,0.0,Winter
4,27-Jan-18,2018,1,5.0,10.0,0.0,2.0,0.0,2.0,Winter

In [25]:
#23
temp.mean(axis='index')

Month           6.615784
Mean Temp C     8.926530
Max Temp C     13.672715
Min Temp C      4.148766
Rain mm        18.564862
Snow cm         3.411912
Precip         21.849494
dtype: float64

In [26]:
#24
temp.groupby('Year').Precip.agg(['count','min','max','mean'])

      count   min    max       mean
Year
1937      2  33.8   41.4  37.600000
1938     12   7.1  102.1  48.033333
1939      8  26.4   90.2  59.537500
1940     12  34.0  123.4  74.225000
1941     12  25.1   89.2  52.408333
...     ...   ...    ...        ...
2014    365   0.0   28.0   1.989041
2015    358   0.0   37.0   1.865922
2016    364   0.0   33.0   1.728022
2017    364   0.0   45.0   2.313187
2018    316   0.0   36.0   2.474684

[82 rows x 4 columns]

In [27]:
#25
temp.head()
temp.drop(['Date','Mean Temp C','Max Temp C','Min Temp C','Rain mm','Precip','Season','Year'], axis=1, inplace=True)

In [28]:
temp.head()

   Month  Snow cm
0      1      1.0
1      1      0.0
2      1      5.0
3      1      0.0
4      1      0.0

In [30]:
df = pd.read_csv('Toronto_temp.csv')

In [ ]:
#NEW LIBRARY: BOKEH
#note: use pip install bokeh on cmd before running 

from bokeh.plotting import figure
from bokeh.io import output_file, show
from bokeh.models import SingleIntervalTicker, LinearAxis

output_file('average-temperatures.html')
f = figure(x_axis_type=None)

monthly_mean = df.groupby('Month').mean()
months = monthly_mean.index
averages = monthly_mean['Mean Temp (C)']

#get all temperatures
temps = []
for i in range(1,13):
    temps.append(df[df['Month'] == i]['Mean Temp (C)'])

#add temperatures to graph
c = 0
for i in temps:
    f.circle(c+1, temps[c],size=1,legend='Temperatures')
    c+=1
    
f.yaxis.axis_label = 'Temperature (C)'
f.add_layout(LinearAxis(ticker=SingleIntervalTicker(interval=1)), 'below')
f.xaxis.major_label_overrides = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun',
                                 7:'Jul', 8:'Aug', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec'}

f.line(months, averages, color="red", line_dash=[4, 10],legend="Average")

show(f)